package domain

import "errors"

var (
	ErrInvalidCredentials                        = errors.New("invalid email or password")
	ErrInvalidRole                               = errors.New("invalid role")
	ErrGenerateToken                             = errors.New("error generating token")
	ErrInvalidToken                              = errors.New("invalid token")
	ErrMissingToken                              = errors.New("missing bearer token")
	ErrMissingSecret                             = errors.New("SECRET_KEY is not set")
	ErrInitAuthConfig                            = errors.New("failed to init auth config")
	ErrReceptionNotFound                         = errors.New("no active reception found for this PVZ")
	ErrCreateProduct                             = errors.New("error create product")
	ErrDeleteProduct                             = errors.New("error delete product")
	ErrNoProductsInReception                     = errors.New("no products in reception list")
	ErrCreateReception                           = errors.New("error create reception")
	ErrCreateReceptionBecauseOfPreviousReception = errors.New("previous reception is still in progress")
	ErrCloseReception                            = errors.New("error close reception")
	ErrCreateUser                                = errors.New("error create user")
	ErrUserWithSuchEmailAlreadyExists            = errors.New("user with such email already exists")
	ErrFindUser                                  = errors.New("no such user")
	ErrCreatePVZ                                 = errors.New("error create pvz")
	ErrGetPVZInfo                                = errors.New("error get pvz info")
	ErrRegisterUser                              = errors.New("error register user")
	ErrMethodNotImplemented                      = errors.New("not implemented")
	ErrGetPVZ                                    = errors.New("error get pvz")
	ErrInvalidInputData                          = errors.New("invalid input data")
	ErrInvalidCity                               = errors.New("invalid city")
	ErrInvalidProductType                        = errors.New("invalid product type")
	ErrEmptyPvzID                                = errors.New("empty pvz id")
)
